# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[34,)"

issueTrackerURL = "https://github.com/Kevun1/Spice-of-Life-Potato-Edition/issues"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/spice-of-life-potato-edition"
logoFile = "logo 160.png"
license = "LGPL-2.1"
credits = "Spice of Life: Carrot Edition team, which this project was forked from."
authors = "Kevun1"

[[mods]]
	modId = "solpotato"
	version = "${file.jarVersion}"
	displayName = "Spice of Life: Potato Edition"
	description = '''
A mod designed to encourage dietary variety!

It does so by rewarding the player with customizable benefits depending on how diverse their diet is. These benefits
require maintaining a diverse diet, rather than a one time consumption.
Instead of using the carrot, we use the potato! Whatever that means...
'''

# Dependencies are optional.
[[dependencies]]
	modId = "forge"
	mandatory = true
	versionRange = "[34,)"
	ordering = "NONE" # BEFORE or AFTER required if the relationship is not mandatory
	side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.16.3, )"
	ordering = "NONE"
	side = "BOTH"
